axon:
  serializer:
    events: jackson
    messages: jackson
    general: jackson

camunda:
  bpm:
    default-serialization-format: application/json
    eventing:
      task: false # Needs to be switched off for Camunda 7.18 and Polyflow >= 3.5

polyflow:
  integration:
    client:
      camunda:
        application-name: ${spring.application.name}  # default
    collector:
      camunda:
        application-name: ${spring.application.name}
        process-definition:
          enabled: false
        process-instance:
          enabled: false
        processVariable:
          enabled: false
        task:
          enabled: true
          enricher:
            type: custom
          importer:
            enabled: true
            task-filter-type: eventstore
          excluded-task-event-names: assignment # even if not used in polyflow, but generally ignore
          excluded-history-event-names: add-identity-link, delete-identity-link # ignore historic events used for assignment
    sender:
      enabled: true
      task:
        enabled: true
        send-within-transaction: true
        type: tx
      data-entry:
        enabled: true
        type: simple
        application-name: ${spring.application.name}
logging:
  level:
    io.holunda.polyflow.taskpool.sender.task: TRACE
