version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    labels:
      - "Technical Debt"
  - package-ecosystem: "maven"
    directory: "platform"
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    labels:
      - "Technical Debt"
  - package-ecosystem: "maven"
    directory: "connect"
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    labels:
      - "Technical Debt"
