# Use this only in dev environments. It's not intended for production usage.
version: '3.9'
services:

  postgres:
    build:
      context: ./postgres
    image: miranum_postgres:0.0.1
    container_name: postgres
    env_file:
      - './.env'
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "psql -l | grep keycloak | wc -l" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${ENGINE_DATASOURCE_DB},${SCHEMA_DATASOURCE_DB},${SSO_DATASOURCE_DB},${S3INTEGRATION_DATASOURCE_DB}
      - POSTGRES_PASSWORD=${LOCAL_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${LOCAL_DATASOURCE_USERNAME}
    networks:
      - internal

networks:
  local-keycloak:
  internal:
