global:
  image:
    tag: 0.1.0-SNAPSHOT # miranum platform image versions (defined in parent pom)

identity:
  keycloak:
    image:
      repository: bitnami/keycloak
      tag: 19.0.3
    postgresql:
      image:
        repository: bitnami/postgresql
        tag: 15.3.0
