apiVersion: v2
name: miranum-platform
version: 0.1.0-SNAPSHOT
appVersion: 1.0.0-SNAPSHOT
description: |
  Miranum Platform Self-Managed Helm charts.
  Miragon's process automation platform based on Camunda Platform powered by Open-Source Technology.
type: application
home: https://github.com/Miragon/miranum-platform
sources:
  - https://github.com/Miragon/miranum-platform
keywords:
  - bpm
  - bpmn
  - process-engine
dependencies:
  # Miranum Platform charts.
  - name: engine
    version: 1.0.0
    import-values:
      - child: image
        parent: global.identity.image
