feign:
  client:
    config:
      default:
        url: "http://localhost:8083/engine-rest/"

spring:
  application:
    name: '@project.artifactId@'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SSO_ISSUER_URL}
      client:
        provider:
          keycloak:
            issuer-uri: ${SSO_ISSUER_URL}
            user-info-uri: ${SSO_BASE_URL}/realms/${SSO_REALM}/protocol/openid-connect/userinfo
            # jwk-set-uri: ${SSO_BASE_URL}/realms/${SSO_REALM}/protocol/openid-connect/certs
            user-name-attribute: user_name
        registration:
          keycloak:
            provider: keycloak
            client-id: ${SSO_ENGINE_CLIENT_ID}
            client-secret: ${SSO_ENGINE_CLIENT_SECRET}
            scope: email, profile, openid
miranum:
  # override default security settings
  security:
    permittedUrls:
      - "/error"
      - "/actuator/**"
      - "/engine-rest/deployment"
      - "/api/deployment"
      - "/swagger-ui/index.html" # allow access to swagger
      - "/swagger-ui*/*swagger-initializer.js" # allow access to swagger
      - "/swagger-ui*/**" # allow access to swagger
      - "/v3/api-docs/*" # allow access to swagger
      - "/v3/api-docs" # allow access to swagger
      - "/camunda/**" # allow camunda webapps
