server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schemadb
    username: sa
    password: changeME!234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
