server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/schemadb
    username: schema-user
    password: schema-secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db
