server:
  port: 8080

spring:
  datasource:
    url:
    driverClassName:
    username:
    password:
  jpa:
    database-platform:
  flyway:
    enabled: true
    locations: "classpath:db/migration/{vendor}"
