name: Build Application

on:
  pull_request:
  push:

jobs:
  # maven build if branch != main
  # if branch main == dev build and release docker images with dev tag
  maven-build:
    uses: ./.github/workflows/workflow-build-and-release-services.yml
    with:
      docker-release-version: dev
      snapshot-release: true
      maven-release: false
      docker-release: ${{ github.ref_name == 'main' }}
      release-connect: ${{ github.ref_name == 'main' }}
      release-platform: ${{ github.ref_name == 'main' }}
    secrets: inherit

  labelPR:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        if: github.event_name == 'pull_request'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml
