name: Build Application

on:
  pull_request:
  push:
    branches-ignore:
      - dev

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: PREP / Check out Git repository
        uses: actions/checkout@v4
      - name: PREP / Install Java and Maven
        uses: actions/setup-java@v4
      - name: BUILD / Build with Maven
        run: |
         chmod +x ./mvnw
         ./mvnw --batch-mode clean install

  labelPR:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        if: github.event_name == 'pull_request'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml
