name: Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release Tag'
        required: false
        default: 'services_XXX_apps_XXX'
      release-connect:
        description: 'Release miranum connect?'
        required: false
        default: false
      connect-maven-new-version:
        description: '(Optional) Specify new maven version - SNAPSHOT will be added to the version'
        required: false
      release-platform:
        description: 'Release miranum platform?'
        required: false
        default: false
      platform-maven-new-version:
        description: '(Optional) Specify new maven version - SNAPSHOT will be added to the version'
        required: false

jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - name: PREP / Check out Git repository
        uses: actions/checkout@v4
      - name: PREP / Prepare mvnw
        run: chmod +x ./mvnw
      - name: PREP / Remove snapshot from services
        run: ./mvnw versions:set --batch-mode -DremoveSnapshot -DprocessAllModules
      - name: PREP / Set services release version env variables
        run: |
          echo "CONNECT_RELEASE_VERSION=$(./mvnw -f connect help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "PLATFORM_RELEASE_VERSION=$(./mvnw -f platform help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    outputs:
      connect-release-version: ${{ env.CONNECT_RELEASE_VERSION }}
      platform-release-version: ${{ env.PLATFORM_RELEASE_VERSION }}

  release:
    needs: release-version
    uses: ./.github/workflows/workflow-build-and-release-services.yml
    with:
      docker-release-version: ${{ needs.release-version.outputs.platform-release-version }}
      snapshot-release: false
      maven-release: true
      docker-release: true
      release-connect: ${{ inputs.release-connect }}
      release-platform: ${{ inputs.release-platform }}
    secrets: inherit

  github-release:
    needs: release-services
    uses: ./.github/workflows/workflow-github-release.yaml
    with:
      release-tag: ${{ github.event.inputs.release-tag }}
    secrets: inherit

  bump-versions:
    needs: github-release
    uses: ./.github/workflows/workflow-bump-version.yaml
    with:
      connect-new-maven-version: ${{ github.event.inputs.connect-maven-new-version }}
      platform-new-maven-version: ${{ github.event.inputs.platform-maven-new-version }}
    secrets: inherit
