name: Release services

on:
  workflow_call:
    inputs:
      release-version:
        description: 'Services release version'
        type: string
        required: false
      snapshot-release:
        description: 'Snapshot release?'
        type: boolean
        required: true
        default: false
      maven-release:
        description: 'Release maven'
        type: boolean
        required: true
        default: true
      docker-release:
        description: 'Release docker images'
        type: boolean
        required: true
        default: true

jobs:
  release-services:
    runs-on: ubuntu-latest
    steps:
      - name: PREP / Check out Git repository
        uses: actions/checkout@v4
      - name: PREP / Install Java and Maven
        uses: actions/setup-java@v4
      - name: PREP / Set up QEMU
        if: inputs.docker-release == true
        uses: docker/setup-qemu-action@v3
      - name: PREP / Set up Docker Buildx
        if: inputs.docker-release == true
        uses: docker/setup-buildx-action@v3
      - name: PREP / Login to DockerHub
        if: inputs.docker-release == true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_MIRAGON_USERNAME }}
          password: ${{ secrets.DOCKER_MIRAGON_PASSWORD }}


      - name: BUILD / Build with Maven
        if: inputs.maven-release == false
        run: |
          chmod +x ./mvnw
          ./mvnw --batch-mode clean install

      - name: RELEASE / Build and Release Maven
        if: inputs.maven-release == true
        # TODO other command
        run: |
          chmod +x ./mvnw
          ./mvnw --batch-mode clean install

      - name: DOCKER / BUILD & PUBLISH / miragon/miranum-camunda7-engine-service
        uses: docker/build-push-action@v5
        with:
          context: ./platform/services/miragon/camunda7-engine-service/.
          push: true
          tags: miragon/miranum-camunda7-engine-service:${{ env.RELEASE_VERSION }}
          platforms: linux/amd64, linux/arm64/v8
      - name: DOCKER / BUILD & PUBLISH / miragon/miranum-deployment-service
        uses: docker/build-push-action@v5
        with:
          context: ./platform/services/deployment-service/.
          push: true
          tags: miragon/miranum-deployment-service:${{ env.RELEASE_VERSION }}
          platforms: linux/amd64, linux/arm64/v8
