name: Release services

on:
  workflow_call:
    inputs:
      release-version:
        description: 'Services release version'
        type: string
        required: false
      snapshot-release:
        description: 'Snapshot release?'
        type: boolean
        required: true
        default: false
      maven-release:
        description: 'Release maven'
        type: boolean
        required: true
        default: true
      docker-release:
        description: 'Release docker images'
        type: boolean
        required: true
        default: true

jobs:
  release-services:
    runs-on: ubuntu-latest
    steps:
      - name: PREP / Check out Git repository
        uses: actions/checkout@v4
      - name: PREP / Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: "ossrh"
          server-username: ${{ secrets.nexus_username }}
          server-password: ${{ secrets.nexus_password }}
      - name: PREP / Set up QEMU
        if: inputs.docker-release == true
        uses: docker/setup-qemu-action@v3
      - name: PREP / Set up Docker Buildx
        if: inputs.docker-release == true
        uses: docker/setup-buildx-action@v3
      - name: PREP / Login to DockerHub
        if: inputs.docker-release == true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_MIRAGON_USERNAME }}
          password: ${{ secrets.DOCKER_MIRAGON_PASSWORD }}


      - name: BUILD / Build with Maven
        if: inputs.maven-release == false
        run: |
          chmod +x ./mvnw
          ./mvnw --batch-mode clean install

      - name: RELEASE / Remove SNAPSHOT
        if: inputs.snapshot-release == false
        run: |
          chmod +x ./mvnw
          ./mvnw versions:set --batch-mode -DremoveSnapshot -DprocessAllModules

      #
      # The GPG key is stored in the secret using the text 'PGP Private Key' format
      # Import it to GPG keyring and trust it.
      #
      - name: RELEASE / Import GPG key
#        if: inputs.maven-release == true
        run: echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --import --no-tty --batch --yes --always-trust

      #
      # Show available keys. This will hide the key name (since it is in the secrets), but show for example expiration date
      #
      - name: RELEASE / List GPG keys available
#        if: inputs.maven-release == true
        run: gpg --list-secret-keys --keyid-format=long

      - name: RELEASE / Build and Release Maven
        if: inputs.maven-release == true
        run: ./mvnw --batch-mode --no-transfer-progress deploy --activate-profiles release -DskipTests -Dgpg.keyname="${{ secrets.PGP_PRIVATE_KEY }}" -Dgpg.passphrase="${{ secrets.PGP_PRIVATE_KEY_SECRET }}"

      - name: RELEASE / Build and Release Maven
        if: inputs.maven-release == true
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.pgp_private_key }}
          gpg_passphrase: ${{ secrets.pgp_private_key_secret }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}

      - name: DOCKER / BUILD & PUBLISH / miragon/miranum-camunda7-engine-service
        if: inputs.docker-release == true
        uses: docker/build-push-action@v5
        with:
          context: ./platform/services/miragon/camunda7-engine-service/.
          push: true
          tags: miragon/miranum-camunda7-engine-service:${{ env.RELEASE_VERSION }}
          platforms: linux/amd64, linux/arm64/v8
      - name: DOCKER / BUILD & PUBLISH / miragon/miranum-deployment-service
        if: inputs.docker-release == true
        uses: docker/build-push-action@v5
        with:
          context: ./platform/services/deployment-service/.
          push: true
          tags: miragon/miranum-deployment-service:${{ env.RELEASE_VERSION }}
          platforms: linux/amd64, linux/arm64/v8
