server:
  port: '${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9001}'

io:
  miranum:
    deploymentserver:
      rest:
        enabled: true
        targets:
          dev:
            bpmn: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            dmn: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            form: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            config: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
          test:
            bpmn: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            dmn: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            form: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            config: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
          prod:
            bpmn: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            dmn: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            form: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
            config: '${MIRANUM_DEPLOYMENT_EXAMPLE_HOST:http://localhost}:${MIRANUM_DEPLOYMENT_EXAMPLE_PORT:9002}/rest/deployment'
